export const NAVIGATION = {
  help: { title: 'Ajuda', icon: 'help-buoy', route: 'ajuda' },
  search: { title: 'Busca', icon: 'search', route: 'busca' },
  compare: { title: 'Comparar', icon: 'git-compare', route: 'comparar' },
  settings: { title: 'Configurações', icon: 'settings', route: 'configuracoes' },
  favorite: { title: 'Favoritos', icon: 'heart', route: 'favoritos' },
  garage: { title: 'Garagem', icon: 'car-sport', route: 'garagem' },
  best: { title: 'Melhores', icon: 'trophy', route: 'melhores' },
  perfil: { title: 'Perfil', icon: 'person-circle', route: 'perfil' },
  term: { title: 'Termo de uso', icon: 'document', route: 'termo-de-uso' },
  login: { title: 'Entrar', icon: 'enter', route: 'login' },
  logout: { title: 'Sair', icon: 'exit', route: 'logout' },
  admin: { title: 'Admin', icon: 'hammer', route: 'admin' },
  permission: { title: 'Permissões', icon: 'lock-open', route: 'permissao' },
  customer: { title: 'Usuários', icon: 'person', route: 'usuario' },
  carcategories: { title: 'Categorias', icon: 'shapes', route: 'carro-categoria' },
  carbrands: { title: 'Marcas', icon: 'pricetag', route: 'carro-marca' },
  carmodels: { title: 'Modelos', icon: 'car', route: 'carro-modelo' },
  carversions: { title: 'Versões', icon: 'git-network', route: 'carro-versao' },
  caropinions: { title: 'Opiniões de Carros', icon: 'reader', route: 'carro-opinioes' },
  brandopinions: { title: 'Opiniões de Marcas', icon: 'reader', route: 'marca-opinioes' }
};
